name: 'Square Calculator'
description: 'Calculate the square of a number'
inputs:
  num:
    description: 'Input number'
    required: true
    default: "0"
outputs:
  result:
    description: 'The square of the input number'
    value: ${{ steps.square.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Set up Dependencies
      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
    - name: Calculate Square
      id: square
      run: python $GITHUB_ACTION_PATH/src/main.py
      shell: bash