name: 'GPT Based Automatic Code Review'
description: 'Provide code review comments using OpenAI GPT-4.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository.'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API key for GPT.'
    required: true
  OPENAI_API_ENDPOINT:
    description: 'OpenAI Endpoint for GPT.'
    required: true
  OPENAI_API_MODEL:
    description: 'OpenAI API model.'
    required: true
  OPENAI_API_VERSION:
    description: 'OpenAI API version.'
    required: true
  exclude:
    description: 'Glob patterns to exclude files from the diff analysis'
    required: false
    default: ""
  num:
    description: 'Input number'
    required: true
    default: "0"
outputs:
  result:
    description: 'The square of the input number'
    value: ${{ steps.square.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Set up Dependencies
      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
    - name: Code Review
      id: code-review
      run: python $GITHUB_ACTION_PATH/src/main.py
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        OPENAI_API_ENDPOINT: ${{ inputs.OPENAI_API_ENDPOINT }}
        OPENAI_API_MODEL: ${{ inputs.OPENAI_API_MODEL }}
        OPENAI_API_VERSION: ${{ inputs.OPENAI_API_VERSION }}
        exclude: ${{ inputs.exclude }}
        INPUT_NUM: ${{ inputs.num }}
      shell: bash